name = "english-procedural-text-presentation"
compatibility_date = "2023-12-01"

[env.production]
name = "english-procedural-text-presentation"

[[pages_builds]]
project_name = "english-procedural-text-presentation"
